# Generated by Django 4.1.5 on 2023-03-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='availabale',
        ),
        migrations.AddField(
            model_name='profile',
            name='contactno',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='email1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='passion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
